spring.datasource.url=jdbc:h2:mem:meubanco
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URL pública do Nominatim (OpenStreetMap)
nominatim.api.base-url=https://nominatim.openstreetmap.org/